# Generated by Django 5.0.14 on 2026-07-21 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoPlataforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exibir_estatisticas",
                    models.BooleanField(
                        default=True,
                        help_text="Desative para ocultar completamente a faixa de estatísticas.",
                        verbose_name="Exibir faixa de números na página inicial",
                    ),
                ),
                (
                    "usar_dados_reais",
                    models.BooleanField(
                        default=False,
                        help_text="Ativado: mostra municípios, emendas, volume e contratos reais da plataforma. Desativado: mostra os destaques personalizados cadastrados abaixo (recomendado no lançamento, enquanto os números reais ainda são pequenos).",
                        verbose_name="Usar dados reais do banco",
                    ),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração da plataforma",
                "verbose_name_plural": "Configuração da plataforma",
            },
        ),
        migrations.CreateModel(
            name="DestaquePlataforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor",
                    models.CharField(
                        help_text='O número/texto grande. Ex.: "100%", "3", "24/7", "30 dias".',
                        max_length=40,
                        verbose_name="Valor em destaque",
                    ),
                ),
                (
                    "rotulo",
                    models.CharField(
                        help_text='A descrição abaixo do valor. Ex.: "Dados oficiais de Brasília".',
                        max_length=80,
                        verbose_name="Rótulo",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "configuracao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destaques",
                        to="portal.configuracaoplataforma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destaque da página inicial",
                "verbose_name_plural": "Destaques da página inicial",
                "ordering": ["ordem", "id"],
            },
        ),
    ]
