# Generated by Django 5.0.14 on 2026-07-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoplataforma",
            name="imagem_fundo_login",
            field=models.ImageField(
                blank=True,
                help_text="Imagem exibida ao fundo da tela de login única (gestores e administradores). Sem imagem, usa o gradiente institucional.",
                null=True,
                upload_to="login/",
                verbose_name="Foto de fundo da tela de login",
            ),
        ),
    ]
