# Generated by Django 5.0.14 on 2026-07-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_configuracaoplataforma_imagem_fundo_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaoplataforma",
            name="sincronizacao_em_segundo_plano",
            field=models.BooleanField(
                default=True,
                help_text="Ativado: ao clicar em 'Sincronizar', a carga roda em segundo plano e o gestor pode sair da página (o histórico mostra o andamento). Desativado: a página aguarda a carga terminar.",
                verbose_name="Sincronização em segundo plano",
            ),
        ),
    ]
