# Generated by Django 5.0.14 on 2026-07-21 21:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=40, verbose_name="Nº da emenda"),
                ),
                (
                    "parlamentar",
                    models.CharField(
                        max_length=150, verbose_name="Parlamentar (autor)"
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Exercício (ano)")),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        verbose_name="Valor do orçamento (R$)",
                    ),
                ),
                (
                    "area_aplicacao",
                    models.CharField(
                        choices=[
                            ("saude", "Saúde"),
                            ("educacao", "Educação"),
                            ("infraestrutura", "Infraestrutura"),
                            ("assistencia_social", "Assistência Social"),
                            ("custeio", "Custeio"),
                            ("outros", "Outros"),
                        ],
                        default="outros",
                        max_length=30,
                        verbose_name="Área de aplicação",
                    ),
                ),
                (
                    "objeto",
                    models.TextField(blank=True, verbose_name="Objeto / finalidade"),
                ),
                (
                    "data_recebimento",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Data de recebimento do recurso",
                    ),
                ),
                (
                    "codigo_transferegov",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Código no Transferegov"
                    ),
                ),
                (
                    "fonte_importacao",
                    models.CharField(
                        blank=True,
                        help_text="transferegov, cgu ou manual",
                        max_length=30,
                        verbose_name="Fonte da importação",
                    ),
                ),
                (
                    "importado_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Importado em"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emendas",
                        to="tenants.tenant",
                        verbose_name="Município",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emenda",
                "verbose_name_plural": "Emendas",
                "ordering": ["-ano", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Empenho",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=40, verbose_name="Nº do empenho"),
                ),
                ("data_empenho", models.DateField(verbose_name="Data do empenho")),
                (
                    "unidade_executora",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Unidade executora"
                    ),
                ),
                (
                    "projeto_atividade",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Projeto/Atividade"
                    ),
                ),
                (
                    "elemento_despesa",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Elemento de despesa"
                    ),
                ),
                (
                    "fonte",
                    models.CharField(blank=True, max_length=60, verbose_name="Fonte"),
                ),
                (
                    "subfonte",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Subfonte"
                    ),
                ),
                (
                    "fornecedor_cnpj",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="CNPJ do fornecedor"
                    ),
                ),
                (
                    "fornecedor_nome",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Razão social do fornecedor",
                    ),
                ),
                (
                    "objeto",
                    models.TextField(
                        blank=True,
                        help_text="Descrição textual completa do que está sendo adquirido/contratado.",
                        verbose_name="Objeto",
                    ),
                ),
                (
                    "valor_empenhado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        verbose_name="Valor empenhado (R$)",
                    ),
                ),
                (
                    "valor_liquidado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        verbose_name="Valor liquidado (R$)",
                    ),
                ),
                (
                    "valor_pago",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=16,
                        verbose_name="Valor pago (R$)",
                    ),
                ),
                (
                    "processo_administrativo",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="Nº/Ano do processo administrativo",
                    ),
                ),
                (
                    "status_rastreabilidade",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente de Vínculo Contratual"),
                            ("vinculado", "Em Conformidade"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=20,
                        verbose_name="Status de rastreabilidade",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "emenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empenhos",
                        to="emendas.emenda",
                        verbose_name="Emenda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empenho",
                "verbose_name_plural": "Empenhos",
                "ordering": ["-data_empenho", "numero"],
            },
        ),
        migrations.CreateModel(
            name="ContratoPNCP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_contrato",
                    models.CharField(max_length=60, verbose_name="Nº/Ano do contrato"),
                ),
                (
                    "modalidade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pregao_eletronico", "Pregão Eletrônico"),
                            ("pregao_presencial", "Pregão Presencial"),
                            ("concorrencia", "Concorrência"),
                            ("dispensa", "Dispensa de Licitação"),
                            ("inexigibilidade", "Inexigibilidade"),
                            ("leilao", "Leilão"),
                            ("dialogo_competitivo", "Diálogo Competitivo"),
                            ("concurso", "Concurso"),
                        ],
                        max_length=30,
                        verbose_name="Modalidade",
                    ),
                ),
                (
                    "id_pncp",
                    models.CharField(
                        blank=True,
                        help_text="Código sequencial único da contratação no portal nacional.",
                        max_length=80,
                        verbose_name="ID PNCP",
                    ),
                ),
                (
                    "url_pncp",
                    models.URLField(
                        blank=True,
                        help_text="URL direta para a página do contrato em pncp.gov.br.",
                        verbose_name="Link do contrato no PNCP",
                    ),
                ),
                (
                    "url_edital",
                    models.URLField(blank=True, verbose_name="Link do edital"),
                ),
                (
                    "data_assinatura",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de assinatura"
                    ),
                ),
                (
                    "documento_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contratos/",
                        verbose_name="Documento anexo (Termo de Referência / Edital)",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empenho",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos_pncp",
                        to="emendas.empenho",
                        verbose_name="Empenho",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato PNCP",
                "verbose_name_plural": "Contratos PNCP",
                "ordering": ["-data_assinatura"],
            },
        ),
        migrations.AddIndex(
            model_name="emenda",
            index=models.Index(
                fields=["tenant", "ano"], name="emendas_eme_tenant__836ecb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emenda",
            index=models.Index(
                fields=["tenant", "parlamentar"], name="emendas_eme_tenant__1ce747_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emenda",
            unique_together={("tenant", "numero", "ano")},
        ),
        migrations.AlterUniqueTogether(
            name="empenho",
            unique_together={("emenda", "numero")},
        ),
    ]
