# Generated by Django 5.0.14 on 2026-07-21 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador usado na URL, ex.: 'salvador' → emendas.gov.com/salvador/",
                        max_length=80,
                        unique=True,
                        verbose_name="Slug do município",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome do município"),
                ),
                ("uf", models.CharField(blank=True, max_length=2, verbose_name="UF")),
                (
                    "codigo_ibge",
                    models.CharField(
                        blank=True, max_length=7, verbose_name="Código IBGE"
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, max_length=18, verbose_name="CNPJ da Prefeitura"
                    ),
                ),
                (
                    "brasao",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="brasoes/",
                        verbose_name="Brasão / Logo",
                    ),
                ),
                (
                    "cor_primaria",
                    models.CharField(
                        default="#1351B4",
                        max_length=7,
                        verbose_name="Cor primária (hex)",
                    ),
                ),
                (
                    "cor_secundaria",
                    models.CharField(
                        default="#00884A",
                        max_length=7,
                        verbose_name="Cor secundária (hex)",
                    ),
                ),
                (
                    "cor_destaque",
                    models.CharField(
                        default="#FFCD07",
                        max_length=7,
                        verbose_name="Cor de destaque (hex)",
                    ),
                ),
                (
                    "texto_introdutorio",
                    models.TextField(
                        blank=True,
                        help_text="Exibido na página inicial do portal do município. Aceita HTML (rich text) — use para citar leis e resoluções locais, ex.: 'Conforme Resolução nº XXX/Ano - TCM'.",
                        verbose_name="Texto introdutório (HTML)",
                    ),
                ),
                (
                    "avisos",
                    models.TextField(
                        blank=True,
                        help_text="Avisos exibidos em destaque no portal público.",
                        verbose_name="Avisos (HTML)",
                    ),
                ),
                (
                    "ativo",
                    models.BooleanField(default=True, verbose_name="Portal ativo"),
                ),
                (
                    "exigir_recaptcha",
                    models.BooleanField(
                        default=True, verbose_name="Exigir reCAPTCHA antes da consulta"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Município (Tenant)",
                "verbose_name_plural": "Municípios (Tenants)",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="GestorMunicipal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(blank=True, max_length=120, verbose_name="Cargo"),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gestorias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gestores",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gestor municipal",
                "verbose_name_plural": "Gestores municipais",
                "unique_together": {("usuario", "tenant")},
            },
        ),
    ]
