# Generated by Django 5.0.14 on 2026-07-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="ano_inicio_sincronizacao",
            field=models.PositiveIntegerField(
                default=2020,
                help_text="Primeiro exercício a importar das APIs federais. Na primeira sincronização o sistema faz a carga histórica deste ano até a data atual; depois, apenas o que ainda falta é consultado.",
                verbose_name="Ano inicial da sincronização",
            ),
        ),
    ]
