# Generated by Django 5.0.14 on 2026-07-21 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_tenant_ano_inicio_sincronizacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="SincronizacaoEmendas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Exercício")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("executando", "Executando"),
                            ("sucesso", "Sucesso"),
                            ("erro", "Erro"),
                        ],
                        default="executando",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "emendas_criadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Emendas criadas"
                    ),
                ),
                (
                    "emendas_atualizadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Emendas atualizadas"
                    ),
                ),
                (
                    "mensagem_erro",
                    models.TextField(blank=True, verbose_name="Mensagem de erro"),
                ),
                (
                    "iniciado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado em"),
                ),
                (
                    "concluido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sincronizacoes",
                        to="tenants.tenant",
                        verbose_name="Município",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sincronização de emendas",
                "verbose_name_plural": "Sincronizações de emendas",
                "ordering": ["-iniciado_em"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "ano", "status"],
                        name="integration_tenant__efb53f_idx",
                    )
                ],
            },
        ),
    ]
