# Generated by Django 5.0.14 on 2026-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargaNacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Exercício")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("executando", "Executando"),
                            ("sucesso", "Sucesso"),
                            ("erro", "Erro"),
                        ],
                        default="executando",
                        max_length=15,
                        verbose_name="Status",
                    ),
                ),
                (
                    "registros_novos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Registros novos"
                    ),
                ),
                (
                    "registros_atualizados",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Registros atualizados"
                    ),
                ),
                (
                    "mensagem_erro",
                    models.TextField(blank=True, verbose_name="Mensagem de erro"),
                ),
                (
                    "iniciado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Iniciado em"),
                ),
                (
                    "concluido_em",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Concluído em"
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga nacional de emendas",
                "verbose_name_plural": "Cargas nacionais de emendas",
                "ordering": ["-iniciado_em"],
                "indexes": [
                    models.Index(
                        fields=["ano", "status"], name="integration_ano_126a7d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmendaNacional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=40, verbose_name="Nº da emenda"),
                ),
                ("ano", models.PositiveIntegerField(verbose_name="Exercício")),
                (
                    "autor",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Parlamentar (autor)"
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Função orçamentária"
                    ),
                ),
                (
                    "localidade",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Localidade do gasto"
                    ),
                ),
                (
                    "localidade_normalizada",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Sem acentos, em maiúsculas — usada no vínculo com municípios.",
                        max_length=255,
                        verbose_name="Localidade normalizada",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=16,
                        verbose_name="Valor empenhado (R$)",
                    ),
                ),
                (
                    "dados",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Registro completo da API",
                    ),
                ),
                (
                    "importado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Importado em"),
                ),
            ],
            options={
                "verbose_name": "Emenda (base nacional)",
                "verbose_name_plural": "Emendas (base nacional)",
                "indexes": [
                    models.Index(
                        fields=["ano", "localidade_normalizada"],
                        name="integration_ano_19e172_idx",
                    )
                ],
                "unique_together": {("numero", "ano")},
            },
        ),
    ]
